@echo off
echo Killing all Node processes...
taskkill /F /IM node.exe >nul 2>&1

echo Waiting for ports to release...
timeout /t 5 /nobreak >nul

echo Cleaning build directory...
if exist .next rmdir /s /q .next

echo Starting dev server...
npm run dev
