import AdmZip from 'adm-zip';
import type { SeasonPackage } from './types';

/**
 * Download a file from a URL and return as Buffer
 */
async function downloadFile(url: string): Promise<Buffer> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to download file: ${response.statusText}`);
    }
    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch (error) {
    console.error('Error downloading file:', url, error);
    throw error;
  }
}

/**
 * Create a ZIP archive containing all season package files
 */
export async function createSeasonPackageZip(
  pkg: SeasonPackage,
  teamName: string,
  season: string
): Promise<Buffer> {
  const zip = new AdmZip();

  // Add README.txt
  const readme = createReadme(pkg, teamName, season);
  zip.addFile('README.txt', Buffer.from(readme, 'utf-8'));

  // Add PDF reports under /reports directory
  zip.addFile('reports/Final_Budget.pdf', pkg.reports.finalBudget);
  zip.addFile('reports/Transaction_History.pdf', pkg.reports.transactionHistory);
  zip.addFile('reports/Budget_Variance.pdf', pkg.reports.budgetVariance);
  zip.addFile('reports/Audit_Trail.pdf', pkg.reports.auditTrail);

  // Download and add all receipts under /receipts directory
  // Process receipts in batches to avoid overwhelming the server
  const BATCH_SIZE = 5;
  for (let i = 0; i < pkg.receipts.length; i += BATCH_SIZE) {
    const batch = pkg.receipts.slice(i, i + BATCH_SIZE);
    const downloadPromises = batch.map(async (receipt) => {
      try {
        const fileData = await downloadFile(receipt.fileUrl);
        zip.addFile(`receipts/${receipt.fileName}`, fileData);
      } catch (error) {
        console.error(`Failed to download receipt ${receipt.fileName}:`, error);
        // Add error file instead of failing completely
        zip.addFile(
          `receipts/${receipt.fileName}.error.txt`,
          Buffer.from(`Failed to download receipt. Original URL: ${receipt.fileUrl}`, 'utf-8')
        );
      }
    });

    await Promise.all(downloadPromises);
  }

  return zip.toBuffer();
}

/**
 * Generate README.txt content for the season package
 */
function createReadme(pkg: SeasonPackage, teamName: string, season: string): string {
  const { summary } = pkg;

  return `
═══════════════════════════════════════════════════════════════
  SEASON CLOSURE PACKAGE
  ${teamName} - ${season}
═══════════════════════════════════════════════════════════════

Generated: ${summary.generatedAt.toLocaleString()}

═══════════════════════════════════════════════════════════════
  FINANCIAL SUMMARY
═══════════════════════════════════════════════════════════════

Total Income:       $${summary.totalIncome.toFixed(2)}
Total Expenses:     $${summary.totalExpenses.toFixed(2)}
Final Balance:      $${summary.finalBalance.toFixed(2)}

Total Transactions: ${summary.transactionCount}
Receipts Attached:  ${summary.receiptCount}

═══════════════════════════════════════════════════════════════
  PACKAGE CONTENTS
═══════════════════════════════════════════════════════════════

This ZIP archive contains all financial documentation for the
${season} season for ${teamName}.

REPORTS (PDF files in /reports folder):
  • Final_Budget.pdf
    - Complete budget breakdown by category
    - Budget allocations and remaining balances

  • Transaction_History.pdf
    - Complete list of all transactions
    - Date, vendor, amount, category, and description
    - Income and expense summary

  • Budget_Variance.pdf
    - Budget vs actual spending analysis
    - Highlights over-budget categories
    - Percentage utilization by category

  • Audit_Trail.pdf
    - Complete audit trail of all financial actions
    - Timestamps, users, and action details

RECEIPTS (in /receipts folder):
  • ${summary.receiptCount} receipt files
  • Named as receipt-[number]-[transaction-id].[ext]
  • Organized chronologically

═══════════════════════════════════════════════════════════════
  NOTES
═══════════════════════════════════════════════════════════════

• All transactions shown have been approved
• Budget is balanced at $${summary.finalBalance.toFixed(2)}
• All required receipts are included
• This package serves as the official financial record for
  the season

═══════════════════════════════════════════════════════════════
  QUESTIONS?
═══════════════════════════════════════════════════════════════

For questions about this financial package, please contact:
${teamName} Treasurer

Generated by TeamTreasure
https://teamtreasure.com
`.trim();
}
